### ISSUE TITLE
FIXME: AttributeError: 'MainContent' object has no attribute 'internal_local_metadata'

### ISSUE THREAD

**Issue by kn007** [RimSort/RimSort#136]
**Describe the bug**
After update to 1.0.6.2-hf, the program return:
```
[2023-08-12 22:12:27] WARNING: Non-Linux platform detected: using multiprocessing.freeze_support() & setting 'spawn' as MP method
[2023-08-12 22:12:27] ERROR: The main application instantiation has failed with an uncaught exception:
[2023-08-12 22:12:27] ERROR: Traceback (most recent call last):
  File "C:\DATA\tools\RimSort\RimSort.py", line 253, in main_thread
  File "C:\DATA\tools\RimSort\RimSort.py", line 180, in __initialize_content
  File "C:\DATA\tools\RimSort\view\main_content_panel.py", line 1291, in _do_refresh
  File "C:\DATA\tools\RimSort\view\main_content_panel.py", line 498, in __refresh_cache_calculations
  File "C:\DATA\tools\RimSort\view\main_content_panel.py", line 549, in _refresh_external_metadata
AttributeError: 'MainContent' object has no attribute 'internal_local_metadata'
```

**To Reproduce**
1. Running program.

**Expected behavior**
Updated from 1.0.5.5 to the latest version (via in-app update), the application broken.

**Screenshots**
![20230812221856](https://github.com/RimSort/RimSort/assets/6196903/dbf65d71-de84-4b62-b223-51477f3b8d4b)

**Please complete the following information:**
 - OS: Windows
 - RimSort version: 1.0.6.2-hf
 - Please provide a `RimSort.log`: **PLEASE DO NOT DELETE LOG FILE WHEN APP EXIT.**
 - Are you running from Python interpreter or from a compiled RimSort release? RimSort release.

**Additional context**
Nope

**Comment by twstagg** [comment]
@kn007 Please open your RimSort settings.json and set it to "Configured git repo", "Configured file path", or "None" for the steam db or community rules options

I made an oversight and forgot to remove that preset this release. It will be fixed next release.

for more information on this, see: https://github.com/RimSort/RimSort/wiki/User-Guide#external-metadata

feel free to join Discord and ask questions should you have any

**Comment by kn007** [comment]
ok, got it.
